blueprint:
  description: Controls EV charging and optional loads based on PV, battery SoC, and
    peak limits.
  domain: automation
  input:
    battery_soc:
      name: Battery SoC Sensor
      selector:
        entity:
          domain: sensor
    battery_soc_emergency:
      default: 30
      name: Minimum Battery SoC (Emergency)
      selector:
        number:
          max: 100
          min: 0
          step: 1
    battery_soc_min:
      default: 60
      name: Minimum Battery SoC (Normal)
      selector:
        number:
          max: 100
          min: 0
          step: 1
    emergency_override:
      name: Emergency Override
      selector:
        entity:
          domain: input_boolean
    grid_power:
      name: Grid Power Sensor
      selector:
        entity:
          domain: sensor
    heat_pump:
      default: ''
      name: Heat Pump Switch (Optional)
      selector:
        entity:
          domain: switch
    home_consumption:
      name: Home Consumption Sensor
      selector:
        entity:
          domain: sensor
    hyundai_charger:
      name: Hyundai Charging Current
      selector:
        entity:
          domain: number
    peak_p1:
      name: Peak Limit P1
      selector:
        number:
          max: 20
          min: 1
          step: 0.1
    peak_p2:
      name: Peak Limit P2
      selector:
        number:
          max: 20
          min: 1
          step: 0.1
    peak_p3:
      name: Peak Limit P3
      selector:
        number:
          max: 20
          min: 1
          step: 0.1
    peak_p4:
      name: Peak Limit P4
      selector:
        number:
          max: 20
          min: 1
          step: 0.1
    peak_p5:
      name: Peak Limit P5
      selector:
        number:
          max: 20
          min: 1
          step: 0.1
    pv_power:
      name: PV Power Sensor
      selector:
        entity:
          domain: sensor
    sauna:
      default: ''
      name: Sauna Switch (Optional)
      selector:
        entity:
          domain: switch
    tesla_charger:
      name: Tesla Charging Current
      selector:
        entity:
          domain: number
  name: Smart Load Manager with Optional Heat Pump and Sauna
